"use client";

import {Fragment,useEffect,useMemo,useState} from "react";
import appPackage from "../../package.json";
import styles from "./page.module.css";

type Audience="carrier"|"consignee"|"backlog";
type Item={
  month:string;carrier:string;consignee:string;title1or2Signed:boolean;
  carrierTitle2Signed:boolean;consigneeTitle3Signed:boolean;
  number:string;containers:string[];deliveryDate:string;documentUrl:string|null;
};
type TmsTrip={id:string;month:string;carrier:string;client:string;consignee:string;container:string;actualDeliveryDate:string;etrnNumber:string|null;title2Signed:boolean;documentUrl:string|null};
type EntityRow={key:string;name:string;aliases:Set<string>;total:number;signed:number;documents:Item[];trips:TmsTrip[]};

const currentMonth=()=>new Date().toLocaleDateString("sv-SE",{year:"numeric",month:"2-digit",timeZone:"Europe/Moscow"});
const monthName=(value:string,short=false)=>{const [year,month]=value.split("-").map(Number);return year&&month?new Intl.DateTimeFormat("ru-RU",short?{month:"short"}:{month:"long",year:"numeric"}).format(new Date(year,month-1,1)):value;};
const displayName=(value:string)=>{let result=String(value||"Не указано").replace(/\([^)]*по\s+поручению[^)]*\)/giu,"").trim();const quoted=result.match(/[«"]([^»"]{2,})[»"]/u)?.[1];if(quoted)result=quoted;return result.replace(/^(?:общество\s+с\s+ограниченной\s+ответственностью|публичное\s+акционерное\s+общество|акционерное\s+общество|оооо|ооо|пао|ао|ип)\s*/iu,"").replace(/^[«"]|[»"]$/gu,"").trim()||"Не указано";};
const entityKey=(value:string)=>displayName(value).toLocaleUpperCase("ru-RU").replace(/[^A-ZА-ЯЁ0-9]/gu,"");

export default function Statistics(){
  const [items,setItems]=useState<Item[]>([]);
  const [tmsTrips,setTmsTrips]=useState<TmsTrip[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState("");
  const [month,setMonth]=useState(currentMonth),[expanded,setExpanded]=useState<string|null>(null);
  const [rankingMode,setRankingMode]=useState<"best"|"worst">("best"),[audience,setAudience]=useState<Audience>("carrier");
  const load=()=>{setLoading(true);setError("");void fetch("/api/kontur/statistics",{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"Не удалось загрузить статистику");setItems(result.items||[]);setTmsTrips(result.tmsTrips||[]);}).catch(value=>setError(value instanceof Error?value.message:"Ошибка загрузки")).finally(()=>setLoading(false));};
  useEffect(load,[]);

  const months=useMemo(()=>[...new Set(items.map(item=>item.month).filter(value=>/^\d{4}-\d{2}$/.test(value)))].sort((a,b)=>b.localeCompare(a)),[items]);
  const selected=useMemo(()=>items.filter(item=>item.month===month&&(audience!=="consignee"||item.title1or2Signed)),[items,month,audience]);
  const signedFlag=(item:Item)=>audience==="consignee"?item.consigneeTitle3Signed:item.carrierTitle2Signed;
  const totals=useMemo(()=>{const signed=selected.filter(signedFlag).length;return {total:selected.length,signed,unsigned:selected.length-signed};},[selected,audience]);
  const circumference=2*Math.PI*46,signedPercent=totals.total?Math.round(totals.signed/totals.total*100):0;
  const selectedTrips=useMemo(()=>tmsTrips.filter(item=>item.month===month),[tmsTrips,month]);
  const entities=useMemo(()=>{const result=new Map<string,EntityRow>();for(const item of selected){const raw=(audience==="consignee"?item.consignee:item.carrier)||"Не указано",key=entityKey(raw)||"НЕУКАЗАНО",candidate=displayName(raw),row=result.get(key)||{key,name:candidate,aliases:new Set<string>(),total:0,signed:0,documents:[],trips:[]};row.aliases.add(raw);if(candidate.length<row.name.length)row.name=candidate;row.total++;row.documents.push(item);if(signedFlag(item))row.signed++;result.set(key,row);}if(audience==="backlog")for(const trip of selectedTrips){const raw=trip.carrier||"Не указано",key=entityKey(raw)||"НЕУКАЗАНО",candidate=displayName(raw),row=result.get(key)||{key,name:candidate,aliases:new Set<string>(),total:0,signed:0,documents:[],trips:[]};row.aliases.add(raw);if(candidate.length<row.name.length)row.name=candidate;row.trips.push(trip);result.set(key,row);}return [...result.values()].sort((a,b)=>audience==="backlog"?b.trips.length-a.trips.length||b.total-a.total||a.name.localeCompare(b.name,"ru"):b.total-a.total||a.name.localeCompare(b.name,"ru"));},[selected,selectedTrips,audience]);
  const ranked=useMemo(()=>entities.filter(row=>row.name!=="Не указано"&&row.total>0).map(row=>({...row,percent:Math.round(row.signed/row.total*100),unsigned:row.total-row.signed})).sort((a,b)=>rankingMode==="best"?b.signed-a.signed||b.percent-a.percent||b.total-a.total:b.unsigned-a.unsigned||a.percent-b.percent||b.total-a.total).slice(0,5),[entities,rankingMode]);
  const rankingSigned=ranked.reduce((sum,row)=>sum+row.signed,0),rankingTotal=ranked.reduce((sum,row)=>sum+row.total,0),rankingPercent=rankingTotal?Math.round(rankingSigned/rankingTotal*100):0;
  const tripTotals=useMemo(()=>({total:selectedTrips.length,withEtrn:selectedTrips.filter(trip=>trip.etrnNumber).length}),[selectedTrips]);
  const titleNumber=audience==="consignee"?3:2,entityLabel=audience==="consignee"?"Грузополучатель":"Перевозчик";

  return <main className={styles.shell}>
    <header className={styles.topbar}><div>А</div><strong>Создание ЭПД <small>версия {appPackage.version}</small></strong><nav><a href="/workspace">Создание документов</a><a href="/forwarding-orders">Поручения клиентам</a><a href="/control">Контроль подписания</a><a className={styles.active} href="/statistics">Статистика</a><a href="/edo-settings">Настройки ID ЭДО</a></nav></header>
    <section className={styles.content}>
      <header className={styles.heading}><div><small>АНАЛИТИКА ЭТрН</small><h1>Статистика ЭТрН</h1><p>{audience==="carrier"?"Контроль подписания титула 2 перевозчиками.":audience==="consignee"?"Контроль подписания титула 3 грузополучателями после наступления даты доставки.":"Контроль рейсов TMS, для которых еще не выпущена ЭТрН."}</p></div><button onClick={load} disabled={loading}>{loading?"Считаем…":"Обновить"}</button></header>
      {error&&<p className={styles.error}>{error}</p>}
      <section className={styles.audienceSwitch}><button className={audience==="carrier"?styles.on:""} onClick={()=>{setAudience("carrier");setExpanded(null)}}>Перевозчики · титул 2</button><button className={audience==="consignee"?styles.on:""} onClick={()=>{setAudience("consignee");setExpanded(null)}}>Грузополучатели · титул 3</button><button className={audience==="backlog"?styles.on:""} onClick={()=>{setAudience("backlog");setExpanded(null)}}>Backlog TMS</button></section>
      <section className={styles.monthFilter}><label><span>Отчётный месяц</span><select value={month} onChange={event=>setMonth(event.target.value)}><option value={currentMonth()}>{monthName(currentMonth())}{months.includes(currentMonth())?"":" · нет данных"}</option>{months.filter(value=>value!==currentMonth()).map(value=><option value={value} key={value}>{monthName(value)}</option>)}</select></label></section>
      <section className={styles.metrics}>{(audience==="backlog"?[{name:"Фактические рейсы TMS",value:tripTotals.total},{name:"Рейсы с ЭТрН",value:tripTotals.withEtrn},{name:"Backlog без ЭТрН",value:tripTotals.total-tripTotals.withEtrn},{name:"Покрытие рейсов",value:tripTotals.total?`${Math.round(tripTotals.withEtrn/tripTotals.total*100)}%`:"0%"}]:[{name:"ЭТрН в контроле",value:totals.total},{name:`Подписано Т${titleNumber}`,value:totals.signed},{name:audience==="carrier"?"Не подписано Т2":"Отклонения · нет Т3",value:totals.unsigned}]).map(card=><article key={card.name}><span>{card.name}</span><strong>{card.value}</strong></article>)}</section>
      {audience!=="backlog"&&<section className={styles.charts}>
        <article className={`${styles.chartCard} ${styles.monthTotalCard}`}><header><div><small>ОБЪЁМ</small><h2>ЭТрН за {monthName(month)}</h2></div></header><div className={styles.singleBar}><strong>{totals.total}</strong><span><i style={{height:totals.total?"100%":"0"}}/></span><small>{monthName(month,true)}</small></div></article>
        <article className={`${styles.chartCard} ${styles.rankingCard}`}><header><div><small>РЕЙТИНГ</small><h2>{entityLabel} · титул {titleNumber}</h2></div><div className={styles.rankSwitch}><button className={rankingMode==="best"?styles.on:""} onClick={()=>setRankingMode("best")}>Топ‑5 лучших</button><button className={rankingMode==="worst"?styles.on:""} onClick={()=>setRankingMode("worst")}>Топ‑5 худших</button></div></header><div className={styles.rankBody}><div className={styles.miniDonut}><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="46"/><circle className={styles.donutValue} cx="60" cy="60" r="46" strokeDasharray={circumference} strokeDashoffset={circumference*(1-rankingPercent/100)}/></svg><div><strong>{rankingPercent}%</strong><span>{rankingSigned} из {rankingTotal}</span></div></div><ol>{ranked.map(row=><li key={row.key}><span title={row.name}>{row.name}</span><strong><small>{row.signed} / {row.total}</small>{row.percent}%</strong></li>)}{!ranked.length&&<li>Нет данных</li>}</ol></div></article>
        <article className={styles.chartCard}><header><div><small>ПОДПИСАНИЕ</small><h2>Доля подписанных · титул {titleNumber}</h2></div></header><div className={styles.donutWrap}><svg className={styles.donut} viewBox="0 0 120 120"><circle cx="60" cy="60" r="46"/><circle className={styles.donutValue} cx="60" cy="60" r="46" strokeDasharray={circumference} strokeDashoffset={circumference*(1-signedPercent/100)}/></svg><div className={styles.donutLabel}><strong>{signedPercent}%</strong><span>подписано</span></div></div><div className={styles.legend}><div><i className={styles.green}/><span>Подписано Т{titleNumber}</span><strong>{totals.signed}</strong></div><div><i className={styles.red}/><span>{audience==="carrier"?"Не подписано":"Отклонение"}</span><strong>{totals.unsigned}</strong></div></div></article>
      </section>}
      <section className={styles.carrierSection}><header><div><small>{audience==="consignee"?"ГРУЗОПОЛУЧАТЕЛИ":audience==="backlog"?"BACKLOG TMS":"ПЕРЕВОЗЧИКИ"}</small><h2>{audience==="backlog"?`Рейсы и выпуск ЭТрН за ${monthName(month)}`:`Подписание титула ${titleNumber} за ${monthName(month)}`}</h2><p>{audience==="backlog"?"Фактические рейсы взяты из ТТН/CMR по дате доставки на склад; рейсы без ЭТрН образуют backlog.":audience==="carrier"?"Учтены только ЭТрН с наступившей датой доставки.":"Отклонение — Т1 или Т2 подписан, дата доставки наступила, но Т3 не подписан."} Нажмите на строку для проверки реестра.</p></div><span>{entities.length} {audience==="consignee"?"грузополучателей":"перевозчиков"}</span></header>
        <div className={styles.tableWrap}><table><thead><tr>{audience==="backlog"?<><th>Перевозчик</th><th>Рейсы TMS</th><th>С ЭТрН</th><th>Backlog</th><th>Покрытие</th></>:<><th>{entityLabel}</th><th>ЭТрН</th><th>Подписано Т{titleNumber}</th><th>Процент подписания</th></>}</tr></thead><tbody>
          {entities.map(row=>{const percent=row.total?Math.round(row.signed/row.total*100):0,isOpen=expanded===row.key,withEtrn=row.trips.filter(trip=>trip.etrnNumber).length,backlog=row.trips.length-withEtrn,coverage=row.trips.length?Math.round(withEtrn/row.trips.length*100):0,colSpan=audience==="backlog"?5:4;return <Fragment key={row.key}><tr className={styles.carrierRow} onClick={()=>setExpanded(isOpen?null:row.key)} aria-expanded={isOpen}><td><button type="button" className={styles.expandButton}><span>{isOpen?"−":"+"}</span><strong>{row.name}</strong></button>{row.aliases.size>1&&<small className={styles.aliasCount}>Объединено названий: {row.aliases.size}</small>}</td>{audience==="backlog"?<><td>{row.trips.length}</td><td>{withEtrn}</td><td className={backlog?styles.unsigned:styles.signed}>{backlog}</td><td><div className={styles.percentCell}><strong>{withEtrn} / {row.trips.length} · {coverage}%</strong><span><i style={{width:`${coverage}%`}}/></span></div></td></>:<><td>{row.total}</td><td>{row.signed}</td><td><div className={styles.percentCell}><strong>{row.signed} / {row.total} · {percent}%</strong><span><i style={{width:`${percent}%`}}/></span></div></td></>}</tr>{isOpen&&<tr className={styles.detailsRow}><td colSpan={colSpan}>{audience==="backlog"?<div className={styles.tripList}><p>Названия объединены: {[...row.aliases].join(" · ")}</p><div className={styles.tripHead}><span>Рейс / контейнер</span><span>Факт. доставка на склад</span><span>ЭТрН</span><span>Титул 2</span><span>Контур</span></div>{row.trips.map(trip=><div className={styles.tripItem} key={trip.id}><strong>{trip.container}</strong><span>{trip.actualDeliveryDate}</span><span className={trip.etrnNumber?styles.signed:styles.unsigned}>{trip.etrnNumber||"Нет ЭТрН"}</span><span className={trip.title2Signed?styles.signed:styles.unsigned}>{trip.etrnNumber?(trip.title2Signed?"Подписан":"Не подписан"):"—"}</span>{trip.documentUrl?<a className={styles.konturLink} href={trip.documentUrl} target="_blank" rel="noreferrer">↗</a>:<span>—</span>}</div>)}</div>:<div className={styles.documentList}><div className={styles.documentHead}><span>ЭТрН</span><span>Контейнеры</span><span>Дата доставки</span><span>Титул {titleNumber}</span><span>Контур</span></div>{row.documents.map((item,index)=><div className={styles.documentItem} key={`${item.number}-${index}`}><strong>{item.number}</strong><span>{item.containers?.length?item.containers.join(", "):"—"}</span><span>{item.deliveryDate||"—"}</span><span className={signedFlag(item)?styles.signed:styles.unsigned}>{signedFlag(item)?"Подписан":audience==="consignee"?"Отклонение":"Не подписан"}</span>{item.documentUrl?<a className={styles.konturLink} href={item.documentUrl} target="_blank" rel="noreferrer">↗</a>:<span>—</span>}</div>)}</div>}</td></tr>}</Fragment>})}
          {!loading&&!entities.length&&<tr><td colSpan={audience==="backlog"?5:4} className={styles.empty}>За выбранный месяц данных нет</td></tr>}
        </tbody></table></div>
        {audience==="backlog"&&<div className={styles.consigneeBreakdown}><h3>Backlog по грузополучателям</h3>{entities.filter(row=>row.trips.length).map(row=><section key={row.key}><header><strong>{row.name}</strong><span>{row.trips.length} рейсов</span></header><div>{[...row.trips.reduce((groups,trip)=>{const key=entityKey(trip.consignee)||"НЕУКАЗАНО",current=groups.get(key)||{name:displayName(trip.consignee),trips:[] as TmsTrip[]};current.trips.push(trip);groups.set(key,current);return groups;},new Map<string,{name:string;trips:TmsTrip[]}>()).values()].sort((a,b)=>b.trips.length-a.trips.length).map(group=>{const withEtrn=group.trips.filter(trip=>trip.etrnNumber).length,backlog=group.trips.length-withEtrn;return <article key={entityKey(group.name)}><div><strong>{group.name}</strong><small>{group.trips.map(trip=>trip.container).join(", ")}</small></div><span>Рейсы <b>{group.trips.length}</b></span><span>С ЭТрН <b>{withEtrn}</b></span><span className={backlog?styles.unsigned:styles.signed}>Backlog <b>{backlog}</b></span></article>})}</div></section>)}</div>}
      </section>
    </section>
  </main>;
}
